#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-parallel
Version  : 1.9.0
Release  : 10
URL      : https://rubygems.org/downloads/parallel-1.9.0.gem
Source0  : https://rubygems.org/downloads/parallel-1.9.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n parallel-1.9.0
gem spec %{SOURCE0} -l --ruby > rubygem-parallel.gemspec

%build
gem build rubygem-parallel.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
parallel-1.9.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/parallel-1.9.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/parallel-1.9.0/MIT-LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/parallel-1.9.0/lib/parallel.rb
/usr/lib64/ruby/gems/2.3.0/gems/parallel-1.9.0/lib/parallel/processor_count.rb
/usr/lib64/ruby/gems/2.3.0/gems/parallel-1.9.0/lib/parallel/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/parallel-1.9.0.gemspec
